### ISSUE TITLE
Multi-Quote button should work in the new loaded comments

### ISSUE THREAD

**Issue by ReeganExE** [green-leaves/infinite-voz#2]
Seem the Multi-Quote button doesn't work in the new loaded comments.

Steps:
1. Scroll to new pages
2. Click on Multi-Quote button of comments
3. Nothing happens

Expected: Comment should be marked as quoted after clicking on Muti-Quote button.
Actual: Nothing happends.

**Comment by green-leaves** [comment]
Fixed in 0.4 version

**Comment by ReeganExE** [comment]
You did override #1 changes.

**Comment by green-leaves** [comment]
Oh sorry just realize that, messing up in my local repository, can you do the PR again?

**Comment by green-leaves** [comment]
reverted your changes
